// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://crkgabcjxkdpnhipvugu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNya2dhYmNqeGtkcG5oaXB2dWd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1MTIwNzcsImV4cCI6MjA2NzA4ODA3N30.3bvJMUiAF-mmC-CWkpNIMF-pKeOp6J_EoyYThgLpLqU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});